# Generated by Django 3.1.7 on 2021-03-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210320_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='deleted',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
    ]
